collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5645409
  brandStrength: 0
  lightness: 0.6433701
  brandColors:
    - '#FFFFFF'
    - '#3288BD'
    - '#9D9AC7'
    - '#FF9237'
    - '#535353'
  rhythmicContrast: 0.07469105
typography_spectrum: 0.4022556
layout_spectrum: 0.3131042
name: Grant Geske
